# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.mesures
canonical:  https://interop.esante.gouv.fr/ig/fhir/mesures
name: Mesures
title: Guide d'implémentation FHIR - Mesures de santé
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 3.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
# releaseLabel: ci-build
# releaseLabel: working
releaseLabel: final-text
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
  shownav: 'true'

dependencies:
  hl7.fhir.fr.core: 2.0.1
  hl7.fhir.uv.phd: 1.0.0
  ans.fr.nos: 1.2.0

pages:
    index.md: 
      title: Accueil
    Le-flux-d-alimentation-des-mesures.md:
      title: Le flux d'alimentation des mesures de santé
    Les-profils-utilises-pour-les-mesures-de-sante.md:
      title: Les profils utilisés pour les mesures de santé
    Le-profil-FHIR-des-objets-connectes.md:
      title: Le profil FHIR des objets connectés
    Terminologies.md:
      title: Terminologies
    downloads.md:
        title: Téléchargements et usages


menu:
  Accueil: index.html
  Les profils Mesures:
    Flux d'alimentation des mesures : Le-flux-d-alimentation-des-mesures.html
    Les profils utilisés pour les mesures de santé: Les-profils-utilises-pour-les-mesures-de-sante.html
    Le profil FHIR des objets connectés: Le-profil-FHIR-des-objets-connectes.html
  Les extensions Mesures:
    MesDiabetisType - Types de diabète: StructureDefinition-mesures-diabetis-type.html
    MesReasonForMeasurement - Motif de la mesure: StructureDefinition-mesures-reason-for-measurement.html
    MesMomentOfMeasurement - Moment de la mesure: StructureDefinition-mesures-moment-of-measurement.html
    MesNumberOfDays - Nombre de jours: StructureDefinition-mesures-number-of-days.html
  Ressources de conformité: artifacts.html
  Terminologies: Terminologies.html
  Autres ressources:
      Téléchargements et usages: downloads.html
      "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
      "Site de l'ANS ": new-tab https://esante.gouv.fr
  Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/


  
